// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MiniProject.Models;

namespace MiniProject.Migrations
{
    [DbContext(typeof(GoalContext))]
    [Migration("20190517212730_MiniProject.Models.StepContextSeed")]
    partial class MiniProjectModelsStepContextSeed
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("MiniProject.Models.Goal", b =>
                {
                    b.Property<long>("GoalId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("GoalName");

                    b.HasKey("GoalId");

                    b.ToTable("Goals");

                    b.HasData(
                        new
                        {
                            GoalId = 1L,
                            GoalName = "Find Product"
                        },
                        new
                        {
                            GoalId = 2L,
                            GoalName = "Select Product"
                        },
                        new
                        {
                            GoalId = 3L,
                            GoalName = "Buy Product"
                        });
                });

            modelBuilder.Entity("MiniProject.Models.Step", b =>
                {
                    b.Property<long>("StepId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<long>("GoalId");

                    b.Property<string>("StepName");

                    b.HasKey("StepId");

                    b.HasIndex("GoalId");

                    b.ToTable("Steps");

                    b.HasData(
                        new
                        {
                            StepId = 1L,
                            GoalId = 1L,
                            StepName = "visit website"
                        },
                        new
                        {
                            StepId = 2L,
                            GoalId = 1L,
                            StepName = "search product"
                        },
                        new
                        {
                            StepId = 3L,
                            GoalId = 1L,
                            StepName = "order search results"
                        },
                        new
                        {
                            StepId = 4L,
                            GoalId = 2L,
                            StepName = "order product detail"
                        },
                        new
                        {
                            StepId = 5L,
                            GoalId = 2L,
                            StepName = "compare product"
                        },
                        new
                        {
                            StepId = 6L,
                            GoalId = 3L,
                            StepName = "sign up"
                        },
                        new
                        {
                            StepId = 7L,
                            GoalId = 3L,
                            StepName = "add to basket"
                        },
                        new
                        {
                            StepId = 8L,
                            GoalId = 3L,
                            StepName = "place order"
                        },
                        new
                        {
                            StepId = 9L,
                            GoalId = 3L,
                            StepName = "make payment"
                        });
                });

            modelBuilder.Entity("MiniProject.Models.Step", b =>
                {
                    b.HasOne("MiniProject.Models.Goal", "Goal")
                        .WithMany("Steps")
                        .HasForeignKey("GoalId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
